### ISSUE TITLE
Cannot get instances to form a cluster

### ISSUE THREAD

**Issue by kenwdelong** [meltmedia/jgroups-aws#8]
I am following your instructions but cannot get my instances to join together.  Maybe I'm forgetting something?

I'm using JGroups to distribute EhCache 2.6.8 http://ehcache.org/documentation/2.6/replication/jgroups-replicated-caching.  My ehcache.xml file looks like:

	<cacheManagerPeerProviderFactory
		class="net.sf.ehcache.distribution.jgroups.JGroupsCacheManagerPeerProviderFactory"
		properties="connect=TCP(bind_port=7800):
		   com.meltmedia.jgroups.aws.AWS_PING(timeout=3000;port_number=7800;tags=Env,Role;log_aws_error_messages=true):         
		   MERGE2(min_interval=10000;max_interval=30000):
		   FD_SOCK:
		   FD(timeout=3000;max_tries=3):
		   VERIFY_SUSPECT(timeout=1500):
		   pbcast.NAKACK(retransmit_timeout=3000;use_mcast_xmit=false):
		   UNICAST:
		   pbcast.STABLE(stability_delay=1000;desired_avg_gossip=50000;max_bytes=4M):
		   pbcast.GMS(join_timeout=5000;print_local_addr=true;view_bundling=true):
		   pbcast.STATE_TRANSFER"
		propertySeparator="::" />

In the logs, we see this upon startup:

2015-07-01 00:58:57.889 DEBUG [localhost-startStop-1] [com.meltmedia.jgroups.aws.AWS_PING]

Configured with tags [[Env, Role]]

2015-07-01 00:58:58.999 DEBUG [localhost-startStop-1] [com.meltmedia.jgroups.aws.AWS_PING] Describing AWS instances with the following filters [[{Name: tag:Rol
e,Values: [API]}, {Name: tag:Env,Values: [PROD]}]]
2015-07-01 00:58:58.999 DEBUG [localhost-startStop-1] [com.meltmedia.jgroups.aws.AWS_PING] Making AWS Request {{InstanceIds: [],Filters: [{Name: tag:Role,Value
s: [API]}, {Name: tag:Env,Values: [PROD]}],}}
2015-07-01 00:58:59.111 DEBUG [localhost-startStop-1] [com.meltmedia.jgroups.aws.AWS_PING] Instances found [[10.0.2.233, 10.0.3.188]]
2015-07-01 00:59:02.147 DEBUG [localhost-startStop-1] [org.jgroups.protocols.pbcast.NAKACK]
[prod-tomcat-api-2b-1-53235 setDigest()]
existing digest:  []
new digest:       prod-tomcat-api-2b-1-53235: [0 (0)]
resulting digest: prod-tomcat-api-2b-1-53235: [0 (0)]
2015-07-01 00:59:02.148 DEBUG [localhost-startStop-1] [org.jgroups.protocols.pbcast.GMS] prod-tomcat-api-2b-1-53235: installing view [prod-tomcat-api-2b-1-53235|0] [prod-tomcat-api-2b-1-53235]
2015-07-01 00:59:02.154 DEBUG [localhost-startStop-1] [org.jgroups.protocols.pbcast.STABLE] resuming message garbage collection
2015-07-01 00:59:02.154 DEBUG [localhost-startStop-1] [org.jgroups.protocols.FD_SOCK] VIEW_CHANGE received: [prod-tomcat-api-2b-1-53235]
2015-07-01 00:59:02.190 DEBUG [localhost-startStop-1] [org.jgroups.protocols.pbcast.STABLE] [ergonomics] setting max_bytes to 4MB (1 members)
2015-07-01 00:59:02.191 DEBUG [localhost-startStop-1] [org.jgroups.protocols.pbcast.STABLE] resuming message garbage collection
2015-07-01 00:59:02.196 DEBUG [localhost-startStop-1] [org.jgroups.protocols.pbcast.GMS] created group (first member). My view is [prod-tomcat-api-2b-1-53235|0], impl is org.jgroups.protocols.pbcast.CoordGmsImpl
2015-07-01 00:59:02.336 INFO  [localhost-startStop-1] [net.sf.ehcache.distribution.jgroups.JGroupsCacheManagerPeerProvider] JGroups Replication started for 'hatch-api'. JChannel: local_addr=prod-tomcat-api-2b-1-53235
cluster_name=hatch-api
my_view=[prod-tomcat-api-2b-1-53235|0] [prod-tomcat-api-2b-1-53235]
connected=true
closed=false
discard_own_messages=true
state_transfer_supported=true
props=TCP(discard_incompatible_packets=true;thread_pool_max_threads=10;ergonomics=true;enable_unicast_bundling=false;port_range=50;conn_expire_time=0;recv_buf_size=150000;thread_naming_pattern=cl;send_buf_size=150000;tcp_nodelay=true;stats=true;oob_thread_pool_enabled=true;oob_thread_pool_rejection_policy=discard;id=22;thread_pool_rejection_policy=Discard;logical_addr_cache_max_size=500;use_send_queues=true;loopback=true;timer_rejection_policy=run;sock_conn_timeout=2000;oob_thread_pool_min_threads=2;send_queue_size=10000;max_bundle_timeout=20;enable_diagnostics=true;external_port=0;oob_thread_pool_max_threads=10;log_discard_msgs=true;name=TCP;oob_thread_pool_keep_alive_time=30000;bind_addr=/fe80:0:0:0:9d:eeff:fee5:c543%eth0;wheel_size=200;bundler_capacity=200000;tick_time=50;timer_max_threads=10;thread_pool_queue_enabled=true;enable_bundling=true;oob_thread_pool_queue_enabled=true;thread_pool_keep_alive_time=30000;bind_port=7800;thread_pool_min_threads=2;reaper_interval=0;bind_interface_str=;diagnostics_ttl=8;logical_addr_cache_expiration=120000;peer_addr_read_timeout=1000;oob_thread_pool_queue_max_size=500;linger=-1;diagnostics_addr=/ff0e:0:0:0:0:0:75:75;receive_on_all_interfaces=false;timer_queue_max_size=500;thread_pool_queue_max_size=500;max_bundle_size=64000;timer_min_threads=4;thread_pool_enabled=true;bundler_type=new;timer_keep_alive_time=5000;timer_type=new;diagnostics_port=7500)
:com.meltmedia.jgroups.aws.AWS_PING(credentials_provider_class=com.amazonaws.auth.DefaultAWSCredentialsProviderChain;ergonomics=true;port_range=50;stagger_timeout=0;timeout=3000;tags=Env,Role;log_aws_error_messages=true;num_initial_srv_members=0;break_on_coord_rsp=true;stats=true;port_number=7800;num_initial_members=10;name=AWS_PING;id=600;return_entire_cache=false)
:MERGE2(merge_fast=true;merge_fast_delay=1000;stats=true;min_interval=10000;ergonomics=true;name=MERGE2;id=0;max_interval=30000;inconsistent_view_threshold=1)
:FD_SOCK(get_cache_timeout=1000;sock_conn_timeout=1000;client_bind_port=0;ergonomics=true;start_port=0;port_range=50;suspect_msg_interval=5000;num_tries=3;bind_interface_str=;stats=true;external_port=0;name=FD_SOCK;bind_addr=/fe80:0:0:0:9d:eeff:fee5:c543%eth0;keep_alive=true;id=3)
:FD(stats=true;ergonomics=true;name=FD;max_tries=3;id=2;timeout=3000)
:VERIFY_SUSPECT(num_msgs=1;bind_interface_str=;stats=true;ergonomics=true;name=VERIFY_SUSPECT;bind_addr=/fe80:0:0:0:9d:eeff:fee5:c543%eth0;id=13;timeout=1500;use_icmp=false)
:pbcast.NAKACK(use_mcast_xmit=false;ergonomics=true;xmit_table_msgs_per_row=10000;xmit_table_max_compaction_time=600000;xmit_stagger_timeout=200;print_stability_history_on_failed_xmit=false;retransmit_timeouts=3000;discard_delivered_msgs=true;max_msg_batch_size=100;exponential_backoff=300;xmit_table_num_rows=5;stats=true;xmit_from_random_member=false;log_discard_msgs=true;log_not_found_msgs=true;xmit_table_resize_factor=1.2;name=NAKACK;id=15;max_rebroadcast_timeout=2000;use_mcast_xmit_req=false;use_range_based_retransmitter=true)
:UNICAST(ergonomics=true;xmit_table_msgs_per_row=1000;xmit_table_max_compaction_time=600000;max_retransmit_time=60000;xmit_interval=2000;timeout=400,800,1600,3200;max_msg_batch_size=500;conn_expiry_timeout=60000;xmit_table_num_rows=100;stats=true;xmit_table_resize_factor=1.2;name=UNICAST;id=12;segment_capacity=1000)
:pbcast.STABLE(cap=0.1;stability_delay=1000;stats=true;ergonomics=true;name=STABLE;desired_avg_gossip=50000;max_bytes=4000000;id=16)
:pbcast.GMS(max_join_attempts=0;print_local_addr=true;handle_concurrent_startup=true;view_bundling=true;leave_timeout=1000;log_view_warnings=true;ergonomics=true;resume_task_timeout=20000;use_flush_if_present=true;print_physical_addrs=true;join_timeout=5000;view_ack_collection_timeout=2000;stats=true;num_prev_views=20;merge_timeout=5000;max_bundling_time=50;name=GMS;num_prev_mbrs=50;id=14;log_collect_msgs=true)
:pbcast.STATE_TRANSFER(stats=true;ergonomics=true;name=STATE_TRANSFER;id=17)

My security group has all ports open to itself over TCP.

As you can see, the call to AWS succeeds and finds the two servers.  But the server identities somehow don't seem to make it over to JGroups.

Any ideas?

**Comment by ctrimble** [comment]
What version of `jgroups-aws` are you using?  There was a bug with tag parsing and I do not think it has made it into a release.  This change corrected the issue c4db3faafed1d45c95b925b1e82aa0b00b76a7f7 .

**Comment by ctrimble** [comment]
@kenwdelong I deployed a fresh 1.4.0-SNAPSHOT up to [sonatype's repository](https://oss.sonatype.org/content/repositories/snapshots/com/meltmedia/jgroups/jgroups-aws/).  If this resolves your issue, please let me know and I will prioritize cutting an official release.

**Comment by kenwdelong** [comment]
Thanks for the response!  I am currently using 1.3.0. 

I will try the 1.4.0-SNAPSHOT.  Also, it looks like JGroups is binding to

**Comment by kenwdelong** [comment]
Hmm, the 1.4.0-SNAPSHOT didn't help.  The replicated caches are still not talking to each other.

When you do the 1.4.0 release, might it be a good idea to upgrade the version of JGroups?  3.1.0 is almost 3 years old.  JGroups seems to have frequent releases!

**Comment by ctrimble** [comment]
There was a refactor last year to discovery that we did not have time to pick up.  There is an open ticket with details.

I would help support a PR if the upgrade is important to you, but the work has repeatedly fallen off the priority list on this end.

**Comment by kenwdelong** [comment]
No worries, I finally figured it out.  I needed -Djava.net.preferIPv4Stack=true; apparently the JGroups sockets were binding to IPv6 addresses, and somehow that was not working.

Thanks for your help!

**Comment by ctrimble** [comment]
@kenwdelong This is great news.  Perhaps an info level log about `-Djava.net.preferIPv4Stack=true` is in order.

**Comment by ctrimble** [comment]
@kenwdelong I released 1.3.1 to maven central last night.

**Comment by kenwdelong** [comment]
Thank you sir!
